version: "3.5"
networks:
  lifi-test-network: {}
services:
  db:
    container_name: lifi-test-db
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    networks:
      - lifi-test-network
    volumes:
      - ./storage/mongo/data:/db
  cache:
    container_name: lifi-test-cache
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - lifi-test-network
    volumes:
      - ./storage/redis/data:/data
  api:
    container_name: lifi-test-api
    build:
      context: ./
    depends_on:
      - db
      - cache
    environment:
      MONGO_URI: mongodb://db:27017/scrape-blocks
      REDIS_HOST: cache
    ports:
      - 3000:3000
    command: >
      npm run start
    networks:
      - lifi-test-network
