FROM --platform=linux/amd64 node:19-alpine as base

RUN npm install -g npm@9.2.0

ENV PORT=3000
ENV USER=node
ENV OWNER='node:node'

USER $USER
WORKDIR /home/node/app

FROM base as build
COPY package*.json .
RUN npm ci

FROM build as release
WORKDIR /home/node/app/node_modules
COPY --from=build --chown=$OWNER /home/node/app/node_modules .

WORKDIR /home/node/app
COPY --chown=$OWNER . .

EXPOSE $PORT

RUN npm run build